### ISSUE TITLE
[Bug] Tag editor causes the app to crash or freeze when too many items are being edited

### ISSUE THREAD

**Issue by nirodhvana** [chr56/Phonograph_Plus#203] opened 2024-07-24 12:36 UTC
### Crash log

No crash log appears

### Version

1.8.0  d6bf4b15

### Steps to reproduce the bug

1. open the app
2. Go to albums
3. Select 10 or more items or a playlists
4. open them in a tag editor

Sometimes the app just freezes and crashes when you open the tag editor and other times when you try to save changes

### Environment

Android version 14
Samsung Galaxy A04e

### Screenshots or Screen recordings

This is what happens when the app freezes up
![Imagepipe_21](https://github.com/user-attachments/assets/b55dea6f-10e9-476e-b5e9-81d273adc9d3)

### Other helpful information

Not sure this only happens with alot of items in the tag editor. I got it to save the changes once after 10 tries in an album with 7 or so songs.

So, after some testing even if i dont respond to the close app prompt, the app will crash and go back to a fresh start and it will also crash all the other background processes and refreshes all the other apps

just like @LostExcalibur im having this problem with only opus files

**Comment by chr56** [comment] 2024-07-24 15:28
Sorry, I could not reproduce it.
Maybe this is device specified.
And it would be better if you have crash log when available.
I could not fix or even investigate any bug without enough information collected. Sorry!

**Comment by nishkaamprem** [comment] 2024-07-24 16:05
> Sorry, I could not reproduce it. Maybe this is device specified. And it would be better if you have crash log when available. I could not fix or even investigate any bug without enough information collected. Sorry!

To be specific instead of crashing the app would freeze when i try to save and then android would show a 'phonograph plus is not responding' popup

**Comment by nishkaamprem** [comment] 2024-07-26 11:00
> Sorry, I could not reproduce it. Maybe this is device specified. And it would be better if you have crash log when available. I could not fix or even investigate any bug without enough information collected. Sorry!

I have edited the issue and added some more information pls check it out

**Comment by nishkaamprem** [comment] 2024-08-02 14:27
@chr56 So, after some testing even if i dont respond to the close app prompt, the app will crash and go back to a fresh start and it will also crash all the other background processes and refreshes all the other apps

**Comment by LostExcalibur** [comment] 2024-08-08 03:30
I am experiencing the same issue, the application basically lags out and crashes anytime I enter the tag editor.
This happens on all my music files, which have been downloaded with `yt-dlp` (relevant flags are `--embed-metadata --embed-thumbnail`).
It does not happen on other songs, so i presume the issue lies with some tag that yt-dlp adds.

Here is the environment information :
```
App version:     1.8.1 (1081)
Git Commit Hash: 1956a97a5c4760f3e7dacbc7fe828a784a941575
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 13 (API 33)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             SM8350/lahaina (by Qualcomm) 
Device brand:    OnePlus (by OnePlus)
Device model:    OnePlus9Pro_IND/LE2121 (code OnePlus9Pro)
Build version:   LE2121_13.1.0.593(EX01)
                 (R.159cc68-4eae-182baf)
Language:        fr
Screen:          3032x1440 (dpi 560)
Permissions:     Storage(READ WRITE)
```

**Comment by nishkaamprem** [comment] 2024-09-06 15:06
> I am experiencing the same issue, the application basically lags out and crashes anytime I enter the tag editor. This happens on all my music files, which have been downloaded with `yt-dlp` (relevant flags are `--embed-metadata --embed-thumbnail`) and stored in opus format. It does not happen on other songs, so I presume the issue lies with some tag that yt-dlp adds.
> 
> Here is the environment information :
> 
> ```
> App version:     1.8.1 (1081)
> Git Commit Hash: 1956a97a5c4760f3e7dacbc7fe828a784a941575
> Package name:    player.phonograph.plus
> Release favor:   modernStable
> Android version: 13 (API 33)
> Architecture:    arm64-v8a, armeabi-v7a, armeabi
> Soc:             SM8350/lahaina (by Qualcomm) 
> Device brand:    OnePlus (by OnePlus)
> Device model:    OnePlus9Pro_IND/LE2121 (code OnePlus9Pro)
> Build version:   LE2121_13.1.0.593(EX01)
>                  (R.159cc68-4eae-182baf)
> Language:        fr
> Screen:          3032x1440 (dpi 560)
> Permissions:     Storage(READ WRITE)
> ```
> 
> I can provide some files to reproduce if needed.
> 
> Edit : after looking a little closer, I have some m4a files downloaded the same way, which pose no issue. I guess it has to be with the way tags are embedded in opus files.

@LostExcalibur Can you provide the files for some testing?

**Comment by nishkaamprem** [comment] 2024-09-12 16:09
@LostExcalibur @chr56 any progress  at detecting the cause of the bug?

**Comment by chr56** [comment] 2024-09-13 06:44
Sorry, I have no idea.

I still could not reproduce it. Maybe this is caused due to _**extra large**_ thumbnails like #221 , I guess?

**Comment by nishkaamprem** [comment] 2024-09-13 10:40
> Sorry, I have no idea.
> 
> I still could not reproduce it. Maybe this is caused due to _**extra large**_ thumbnails like #221 , I guess?

@chr56 @LostExcalibur 
Thats exactly what i was trying to do when this bug first occured. I was tryna change the cover for a whole bunch of opus files.
Im guessing it is somehow related to #221

**Comment by chr56** [comment] 2024-09-13 14:25
Try to select excluding these files with large embed images. It looks that _large images_ is the caus.

**Comment by nishkaamprem** [comment] 2024-09-14 02:08
> Try to select excluding these files with large embed images. It looks that _large images_ is the cause.

this only seems to happen with files that already have thumbnails
this may be a memory overload problem due to loading all of the thumbnails already embedded in the opus files. My device has only 3gb ram. So @chr56 may have not been able to reproduce it because you have more ram. This may be caused due to loading the same image for each file, causing to take up too much memory.

It makes sense as when im trying to add thumbnails to a bunch of files without already a thumbnail, the tag editor loads just fine but when i try to load files with thumbnails the tag editor just crashes or freezes up and SOMETIMES EVEN THE ENTIRE ENVIRONMENT CRASHES.

So this problem may not even be limited to only opus files. 

If this is truely the problem then Maybe you could make the app not load previously added thumbnails in the tag editor or smth.

**Comment by chr56** [comment] 2024-09-16 11:53
It look likes that Vorbis Comment Tag causes the problem (In Vorbis Comment, images would be encoded in base64, which would be directly displayed in Phonograph Plus no matter how long or large they are, so that causing such issues). 

Try this [preview](https://github.com/user-attachments/files/17012261/tag-image-test.zip) with special treatment to Vorbis Comment.

**Comment by nirodhvana** [comment] 2024-09-16 14:48
> It look likes that Vorbis Comment Tag causes the problem (In Vorbis Comment, images would be encoded in base64, which would be directly displayed in Phonograph Plus no matter how long or large they are, so that causing such issues).
> 
> Try this [preview](https://github.com/user-attachments/files/17012261/tag-image-test.zip) with special treatment to Vorbis Comment.

Ill try it out

**Comment by nirodhvana** [comment] 2024-09-16 15:30
@chr56 I've been trying it out and it does not crash anymore but sometimes the thumbnail will not update. I'll test some more and report back

**Comment by nirodhvana** [comment] 2024-09-16 16:40
@chr56 It seems it does not crash but the tag editor does not update thumbnails when lots of items are selected.

I tryed twice with an album with 10 and another with 16 items. Both times the editor gave no error but did not update the thumbnail

**Comment by nirodhvana** [comment] 2024-09-28 15:33
@chr56 any progress?

**Comment by chr56** [comment] 2024-09-28 15:48
> @chr56 any progress?

Not any. Nothing has been changed since that.

**Comment by nirodhvana** [comment] 2024-10-16 16:52
> > @chr56 any progress?
> 
> Not any. Nothing has been changed since that.

@chr56 
Will the chanfes in the preciew be merged anytime soon.

**Comment by chr56** [comment] 2024-10-17 00:45
> @chr56 Will the changes in the preview be merged anytime soon.

It should be already in 1.8.5-dev1, and would be finally in 1.8.5 eventually. v1.8.5 may be released on end of this month or next.

**Comment by nirodhvana** [comment] 2024-10-17 10:44
> > @chr56 Will the changes in the preview be merged anytime soon.
> 
> It should be already in 1.8.5-dev1, and would be finally in 1.8.5 eventually. v1.8.5 may be released on end of this month or next.

Thanks, is the issue completely resolved?

**Comment by chr56** [comment] 2024-10-17 13:40
> is the issue completely resolved?

I am not sure. All simple test done by me are fine to me.

Current workaround would truncate text tagfields that are too long. Maybe this is not the best solution, it shall hint a message owing to too long, but doing such things requires more workload, and I may do not more time. It is planned to solve all these issue in a large code refactoring on Tag Editor next time (maybe next year?), as there are already pretty of issues on Tag Editor now.

@nirodhvana

**Comment by chr56** [comment] 2024-11-03 09:06
[v1.8.5](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.5) has released! This issue should be fixed (although imperfect).
Close!

**Closed by chr56** 2024-11-03 09:06 UTC
Labels: Bug

**Comment by nirodhvana** [comment] 2025-03-18 06:54
@chr56 this issue seems to have returned in the newest release.

whenever I open the tag editor with however many opus files, it either shows a black screen and crashes the whole ui or gives the following error when I try to save changes:

> Crash Report:
App version:     1.9.3 (1093)
Git Commit Hash: c2bccefd0c035fc18f532bd867773077257e24ab
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 14 (API 34)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             MT6765V/CB/a04e (by Mediatek) 
Device brand:    samsung (by samsung)
Device model:    a04exx/SM-A042F (code a04e)
Build version:   UP1A.231005.007.A042FXXSAEYA3
                 (A042FXXSAEYA3)
Language:        en
Memory:          1068/2784 
Screen:          1459x720 (dpi 320)
Permissions:     Storage(READ WRITE)
>

>Stacktrace:
java.lang.UnsupportedOperationException: Empty collection can't be reduced.
	at ah.u0.generateMetadataDifference(SourceFile:153)
	at ah.j.invoke(SourceFile:1444)
	at ah.m.d(SourceFile:922)
	at f1.b.d(SourceFile:47)
	at zb.d.r(SourceFile:249)
	at ah.n.c(SourceFile:224)
	at f1.b.i(SourceFile:39)
	at f1.b.c(SourceFile:9)
	at d0.u.d(SourceFile:376)
	at f1.b.d(SourceFile:47)
	at r0.q3.d(SourceFile:160)
	at f1.b.d(SourceFile:47)
	at x0.d.b(SourceFile:142)
	at r0.z0.j(SourceFile:344)
	at e9.t.d(SourceFile:121)
	at f1.b.d(SourceFile:47)
	at g3.d.d(SourceFile:236)
	at f1.b.d(SourceFile:47)
	at a.a.l(SourceFile:152)
	at g3.d.d(SourceFile:199)
	at f1.b.d(SourceFile:47)
	at g3.t.a(SourceFile:46)
	at a0.z1.d(SourceFile:835)
	at f1.b.d(SourceFile:47)
	at x0.d.b(SourceFile:142)
	at j2.k1.a(SourceFile:273)
	at a0.o1.d(SourceFile:527)
	at f1.b.d(SourceFile:47)
	at x0.d.b(SourceFile:142)
	at j2.p0.a(SourceFile:566)
	at j2.n3.d(SourceFile:250)
	at f1.b.d(SourceFile:47)
	at x0.d.a(SourceFile:217)
	at j2.n3.d(SourceFile:213)
	at f1.b.d(SourceFile:47)
	at x0.o.n(SourceFile:202)
	at x0.s.i(SourceFile:31)
	at x0.o1.a(SourceFile:44)
	at x0.n.a(SourceFile:5)
	at x0.n.a(SourceFile:5)
	at x0.n.a(SourceFile:5)
	at x0.s.j(SourceFile:7)
	at a0.b.f(SourceFile:802)
	at j2.r.setOnViewTreeOwnersAvailable(SourceFile:7)
	at j2.o3.c(SourceFile:12)
	at j2.o3.f(SourceFile:19)
	at androidx.lifecycle.y.a(SourceFile:23)
	at androidx.lifecycle.z.a(SourceFile:251)
	at a0.b.f(SourceFile:771)
	at j2.r.onAttachedToWindow(SourceFile:118)
	at android.view.View.dispatchAttachedToWindow(View.java:23227)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3698)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3901)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
>

**Comment by nirodhvana** [comment] 2025-03-18 23:23
> That is not the same issue.

@chr56 this might be related to another issue I just opened 
https://github.com/chr56/Phonograph_Plus/issues/288

**Comment by nirodhvana** [comment] 2025-03-20 13:56
@chr56 the version that fixes https://github.com/chr56/Phonograph_Plus/issues/288 still has this problem
