### ISSUE TITLE
[Bug]  Issue of Multi Selection mode

### ISSUE THREAD

**Issue by eku** [chr56/Phonograph_Plus#176] opened 2024-05-05 14:50 UTC
### Bug Summary

Multi selection for actions, for instance on albums by an artists, are not limited to the number of items.

### Version

1.6.2

### Steps to reproduce the bug

1. Choose an artist with, say 2 albums
2. Long press on first album to start multi selection -> selection is 1
3. Press on second album -> selection is 2
4. Long press on first album -> increases selection count to 5
5. Long press on first album -> increases selection count to 7

### Environment

AOSP 13

### Screenshots or Screen recordings

![Bildschirmfoto vom 2024-05-05 16-44-41](https://github.com/chr56/Phonograph_Plus/assets/418685/13c66755-949b-4d3b-82ac-8f4a2c138cd8)

### Other helpful information

Let me know if you want me to test something.

**Comment by chr56** [comment] 2024-05-06 01:55
This is just a bug of **Range Selection**.
The start one and end one have been added for multiply times, without removing the duplicated.

And other behaviors are **normal** by design: Long press to enter multi-select mode, and then simple click to add and long press to _start range selection_ (but duplicated ones are added here)

**Comment by chr56** [comment] 2024-05-06 03:07
Fix in revision 83269b48

**Comment by chr56** [comment] 2024-05-07 05:09
This fix has been included in [v1.7-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.7-dev2)

**Comment by eku** [comment] 2024-05-07 05:18
Nice. Since I'm using the F-Droid  version and the apk signature differs I have to wait.

**Comment by chr56** [comment] 2024-05-07 07:19
1. Preview version has a different package name.
2. _Reproducible Build_ has enabled, meaning the F-droid apk signature should be replaced **as same as the GitHub one**, because artifacts are same except signature which allow replacing signature.

**Comment by chr56** [comment] 2024-05-08 16:19
> With v1.7-dev2 I cannot select more items then available. Thanks.

Excuse me, I don't get it.

**Comment by eku** [comment] 2024-05-08 16:35
> > With v1.7-dev2 I cannot select more items then available. Thanks.
> 
> Excuse me, I don't get it.

I mean, bug fixed.

**Comment by chr56** [comment] 2024-05-12 12:00
Fix has been backported to [v1.6.3](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.6.3). Close!

> Reproducible Build has enabled, meaning the F-droid apk signature should be replaced as same as the GitHub one.

You can _directly_ install it without signature difficulties.

**Closed** 2024-05-12 12:00 UTC
Labels: Bug

**Comment by eku** [comment] 2024-05-12 12:56
Thanks for fixing.
