### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by soumyabratabose** [chr56/Phonograph_Plus#3] opened 2022-03-16 19:32 UTC
Crash Report:

Package name:    player.phonograph.plus
App version:     0.1.0 (104)
Git Commit Hash: 5f2adcf0a7c0f5156627
Android version: 11 (SDK 30)
Device brand:    lge  (by LGE)
Device model:    LM-G850 (code: mh2lm)
Product name:    mh2lm
Build version:   RKQ1.210420.001 
                 (2202502174aca.OPEN_ESA_DS)
Hardware:        mh2lm
Language:        en

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Invalid column audio_id
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1191)
	at android.content.ContentResolver.query(ContentResolver.java:1122)
	at android.content.ContentResolver.query(ContentResolver.java:1078)
	at player.phonograph.util.PlaylistsUtil.doesPlaylistContain(Unknown Source:38)
	at player.phonograph.util.MusicUtil.isFavorite(Unknown Source:11)
	at player.phonograph.ui.fragments.player.card.CardPlayerFragment$2.a(Unknown Source:17)
	at player.phonograph.ui.fragments.player.card.CardPlayerFragment$2.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by stoponerr** [comment] 2022-03-16 19:35
same issue, running calyxos latest

Crash Report:

Package name:    player.phonograph.plus
App version:     0.1.0 (104)
Git Commit Hash: 5f2adcf0a7c0f5156627
Android version: 12 (SDK 31)
Device brand:    google  (by Google)
Device model:    Pixel 4a (5G) (code: bramble)
Product name:    bramble
Build version:   SQ1D.220205.003.22302000 
                 (22302000)
Hardware:        bramble
Language:        en

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalArgumentException: Invalid column audio_id
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1151)
	at android.content.ContentResolver.query(ContentResolver.java:1107)
	at player.phonograph.util.PlaylistsUtil.doesPlaylistContain(Unknown Source:38)
	at player.phonograph.util.MusicUtil.isFavorite(Unknown Source:11)
	at player.phonograph.ui.fragments.player.card.CardPlayerFragment$2.a(Unknown Source:17)
	at player.phonograph.ui.fragments.player.card.CardPlayerFragment$2.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by chr56** [comment] 2022-03-16 23:58
I am aware of this issue. It seems that it's (favorite) playlist causes this problem.

**Comment by chr56** [comment] 2022-03-17 03:48
Try this:
[preview.zip](https://github.com/chr56/Phonograph_Plus/files/8281231/preview.zip)

@stoponerr @soumyabratabose 

**Note**: please be aware that this is an another app with name `Phonograph Plus Preview`  (along with package name `player.phonograph.plus.preview` ) ,and there would be an another Application named `Phonograph Plus Preview` in your app list (so please test this one)

**Comment by soumyabratabose** [comment] 2022-03-17 12:13
> Try this: [preview.zip](https://github.com/chr56/Phonograph_Plus/files/8281231/preview.zip) (unzip and install the apk inside)
> 
> @stoponerr @soumyabratabose
> 
> **Note**: please be aware that this is an another app with name `Phonograph Plus Preview` (along with package name `player.phonograph.plus.preview` ) ,and there would be an another Application named `Phonograph Plus Preview` in your app list (so please test this one)
> 
> Test Method: Toggle `Favorite` icon, and close app then relaunch

Now, there is no crash on my device

**Comment by chr56** [comment] 2022-03-17 12:18
> > Try this: [preview.zip](https://github.com/chr56/Phonograph_Plus/files/8281231/preview.zip) (unzip and install the apk inside)
> > @stoponerr @soumyabratabose
> > **Note**: please be aware that this is an another app with name `Phonograph Plus Preview` (along with package name `player.phonograph.plus.preview` ) ,and there would be an another Application named `Phonograph Plus Preview` in your app list (so please test this one)
> > Test Method: Toggle `Favorite` icon, and close app then relaunch
> 
> Now, there is no crash on my device

Well, if so, a stable version would be released soon.

**Comment by chr56** [comment] 2022-03-19 07:36
This should be fixed.
Close!

**Closed by chr56** 2022-03-19 07:36 UTC
Labels: bug
