### ISSUE TITLE
[Bug Report] "... keeps stopping"

### ISSUE THREAD

**Issue by uli-on** [chr56/Phonograph_Plus#34] opened 2022-10-04 17:34 UTC
**Describe the bug or unexpected behavior**
On tapping the app icon, after a short while I keep getting this info. Sometimes I can see the mini bottom player with last played title displayed, sometimes even the recent changes screen assembles, sometimes I only see an empty library flashing up before the crash happens. 

**Crash log**
Unfortunately, Scoop (autom. crash logger app) isn't capable of grabbing a crash log of my situation.

**How to reproduce**
For me it's "Tap the app icon". Happens in v0.3.3 and now also in v0.3.4

**Additional info**
I added tracks to the library using other apps while Phonograph was idle for some weeks.
 
Fairphone 3
Android 10, FP3 flavour
Google Play Services upd. to v22.33.16
Webview upd. to 102.0.5005.78

**Comment by chr56** [comment] 2022-10-05 00:33
I am not sure what happened. 
According to your description, it might be a native crash caused by native codes instead of a crash on virtual machine. That might explain why your crash  tracker can not record it.

But Phonograph Plus **has not any of native code**!

So, try to:
1) wipe its cache.
2) or wipe its data if won't work.
3) turn off your crash tracker or add app to whitelist, it might be Scoop's fault.

**Comment by uli-on** [comment] 2022-10-05 13:47
> wipe its data if won't work

That's been the culprit. Thanks! :)
(Unfortunately assigning 107 individual artist images now lies ahead of me.)

So my conclusion is "don't edit music tags in another app if the music library is already built"? (Cause moving/adding files can't be the reason, that's how "life" is.) Or is it "make Phonograph acquainted with the current media before updating the app"? Both?

BTW1 The blacklist section in settings, could it be member of the library section? That's where I looked for it out of habit from other music player apps.

BTW2 Has the layout or naming of buttons in the blacklist selection dialogue changed recently? I seem to remember having less difficulties finding my way through to the external disk.

**Comment by chr56** [comment] 2022-10-07 06:45
Sorry I forget this issue.

1) I am sorry for your loss of images.
Maybe I would rework the `custom artist images` part. For example, moving storage location of artists images to internal storage (`/Android/data/<package-name>`), to make it easier to backup images (?).

2) Actually I have no idea what happened to you on earth. Maybe it's a fault of data-migration from an old version. Have you updated to the latest application from a very old version? It might be a myth and unfixable bug for me due to the lack of crash logs.

3) Well, actually the UI of settings is messy and little of old, becoming a "historical problem" or a "technical debt" (or so-called "sh*t mountain").
I am planning to rework it to make it easier to maintain and add new settings items, including reordering and reclassifying. And it has been in my [to-do list](https://github.com/chr56/Phonograph_Plus/blob/dev/README.md#to-do-list) for a long time. However, I am busy with the other thing, and that's not the first priority. You might have to wait longer for that. (PS: this to-do list is way too "behind the schedule" as well)

4) Yeah, the style of `Blacklist Dialog` had been same with new `Folder Page` style (which was introduced in v0.3.0) since v0.3.2. Because the legacy one used a deprecated library which doesn't support Android 13. See recent changelog for more informations.

**Comment by chr56** [comment] 2022-10-08 12:23
Close, fixed in [v0.3.5.1-LTS](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.5.1-LTS)

**Closed by chr56** 2022-10-08 12:23 UTC
Labels: Bug, Closing
