### ISSUE TITLE
[Bug] Playlist Creation 

### ISSUE THREAD

**Issue by AdityaMishra135** [chr56/Phonograph_Plus#233] opened 2024-10-21 15:18 UTC
### Bug Summary

If create playlists in SAF Mode after its not showing. Other one when creating without SAF mode its toast already exists even it's not exist 

### Version

Latest

**Comment by AdityaMishra135** [comment] 2024-10-21 15:22
https://github.com/user-attachments/assets/0704de3c-3350-4862-8bf9-9fddeb2e20e5

**Comment by chr56** [comment] 2024-10-21 15:32
> If create playlists in SAF Mode after its not showing

Looks that there are still some problems of automatically refreshing list: Refresh manually by pulling down, or consider trying versions after f2d3be82a977ecb61db9a0c6ca85858e715635fd. (I could not reproduce it, however.)

>  Other one when creating without SAF mode its toast already exists even it's not exist

This is confirmed. I would check it later.

**Comment by AdityaMishra135** [comment] 2024-10-21 15:53
https://github.com/user-attachments/assets/51a4c40f-e45b-4370-888f-88d75222f276

Also manually pull to refresh not and also i have another playlist which is not showing.

**Comment by chr56** [comment] 2024-10-24 04:40
------
> Other one when creating without SAF mode its toast already exists even it's not exist

Fixed in 60996074: [Preview-60996074](https://github.com/user-attachments/files/17501026/Preview-60996074.zip)


-----------
> If create playlists in SAF Mode after its not showing

I could not reproduce. Please consider:
- check permission (full access to storage)
- make sure these playlists not on a _PHYSICAL_ SD card (we have problems accessing it)
- try "Scan media" from drawer (to update MediaStore)
- use "add to playlist ..." to create a playlist with actual content (empty playlists may not be detected on some system if so)
- even consider reboot your device (most device would trigger an update of MediaStore similar to "Scan media" but more forceful)

I think it's _device-specified_!

------------

This first issue is _solved_ and it happened only in Preview.
The second issue may not be solved, but we are introducing Database Playlists (as it says, storing in internal database instead of files to bypass such problems) in 1.9.x, if everything goes fine. So, such files playlists issues (especially device-specified ones) would NOT be accepted and would be quickly closed as soon as possible unless it's universal or ubiquitous.


------------
The issue is now **closing**!

Thank you any way!

**Closed** 2024-10-24 04:43 UTC
Labels: Bug
