### ISSUE TITLE
[Bug] Some albums sorted incorrectly (string sort rather than numeric sort)

### ISSUE THREAD

**Issue by AntiSol** [chr56/Phonograph_Plus#228] opened 2024-10-02 10:15 UTC
### Bug Summary

I'm not sure whether this is related to https://github.com/chr56/Phonograph_Plus/issues/227 or not
It seems that some albums (especially the one for this I'm seeing the above bug) are not sorting correctly according to numeric track numbers, but are sorting as if track numbers were strings. For example:
```
1 track 1
10 track 10
2 track 2
20 track 20
21 track 21
3 track 3
```
etc, rather than the expected numeric track order of `1, 2, 3, 10, 20, 21`.

screenshot:
![Screenshot_20241002-193101](https://github.com/user-attachments/assets/39a1ed2e-3236-4aa8-be8d-752f66f6b97d)

Note that this only happens with some albums. I suspect that maybe it's albums which only have an id3v2 (not both v1 and v2), but I haven't been able to confirm this.

### Version

1.8.4

**Comment by chr56** [comment] 2024-10-02 11:54
I _could not reproduce_ (on Android 14).
It looks that it is device-specific. We read from `MediaStore` database of OS and sort them by database as well. It may stored as String instead of Integer on these lower platforms.

But there is a workaround in 54f4832d which sorting it again.

**Comment by AntiSol** [comment] 2024-10-13 13:04
The file I attached to #227 (track 2) exhibits this behaviour for me, did you try with that file? I'll also attach track 10 from the same album here, maybe these will allow you to reproduce :)
[track10.zip](https://github.com/user-attachments/files/17355682/track10.zip)

**Comment by chr56** [comment] 2024-10-17 08:10
![image](https://github.com/user-attachments/assets/46c3c353-d356-421d-8ba0-72ab855dc30c)

Sorry, but 
> _I could not reproduce_!

**Comment by AntiSol** [comment] 2024-10-17 08:50
dammit, I hate computers. Presumably you're right and it's the android version or something then. thanks for trying! :) 

Do you think the workaround you mentioned should solve it once that makes it into a release?

**Comment by chr56** [comment] 2024-10-17 09:22
> Do you think the workaround you mentioned should solve it once that makes it into a release?

I do not know, this workaround is included in latest [Preview ](https://github.com/chr56/Phonograph_Plus/blob/preview_1.8.5-dev2/README.md#downloads) Channel ([preview_1.8.5-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.8.5-dev2)), check it out!

**Comment by AntiSol** [comment] 2024-10-23 13:21
this prevoew does solve it! thanks!

**Comment by chr56** [comment] 2024-11-03 09:13
[v1.8.5](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.5) has been released! 

This issue should be fixed, although the fix may be imperfect or not very elegant.

**Close**! 
Reopen the issue if it happens again, or create a new issue for a similar one or a newly introduced one.

**Closed by chr56** 2024-11-03 09:13 UTC
Labels: Bug, Device-Specific

**Comment by AntiSol** [comment] 2024-11-03 13:35
ah sorry to rain on your parade but I've just today noticed another issue which might be related, which is that the songs show in the correct order in e.g album view, but then when I add them to the playing queue, they are not added in the correct album order.

Let me know if you want me to raise a new bug for this :)

**Comment by chr56** [comment] 2024-11-03 15:29
I see.

**Comment by chr56** [comment] 2024-11-05 02:03
Patch [v1.8.5.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.5.1) _just_ contains the commit.

If not fixed, remind me and wait for next release.
