### ISSUE TITLE
Crash when opening playlist

### ISSUE THREAD

**Issue by unnamedau** [chr56/Phonograph_Plus#178] opened 2024-05-08 05:42 UTC
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.6.2 (1062)
Git Commit Hash: be7844c9854908da5cae636d12fa0b328ce4e6de
Android version: 13 (SDK 33)
Device brand:    samsung  (by samsung)
Device model:    SM-G781W (code: r8q)
Product name:    r8qcsx
Build version:   TP1A.220624.014.G781WVLSDHXC1 
                 (G781WVLSDHXC1)
Hardware:        qcom
Language:        en


Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{player.phonograph.plus/player.phonograph.ui.modules.playlist.PlaylistDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:824)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4865)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
	at android.os.Parcel.readValue(Parcel.java:4544)
	at android.os.Parcel.readValue(Parcel.java:4324)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at m2.b.p(SourceFile:5)
	at lf.o2.invoke(SourceFile:8)
	at zc.a.<init>(SourceFile:3)
	at yc.a.b(SourceFile:5)
	at android.support.v4.media.session.j.j(SourceFile:79)
	at android.support.v4.media.session.j.i(SourceFile:13)
	at gb.b.i0(SourceFile:26)
	at ef.m.a(SourceFile:31)
	at ef.m.invoke(SourceFile:6)
	at o8.b0.getValue(SourceFile:12)
	at player.phonograph.ui.modules.playlist.PlaylistDetailActivity.o(SourceFile:3)
	at player.phonograph.ui.modules.playlist.PlaylistDetailActivity.onCreate(SourceFile:434)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more


```

### Version

1.6.2

### Steps to reproduce the bug

Upon opening any playlist, crashes with this error

### Other helpful information

My playlists are all .m3u files, in case that's part of it
Pressing back closes the crash report and lets me view the playlist anyway, but then the back arrow icon doesn't work and I have to close and re-open Phonograph to use the rest of the app

**Comment by chr56** [comment] 2024-05-08 07:36
Sorry, I can not reproduce.

**Comment by chr56** [comment] 2024-05-11 05:30
Well, I reproduced this on **Android 13** (API 33). 
This looks like a bug of Android: [Google Issue Tracker 242048899](https://issuetracker.google.com/issues/242048899).

It should be fixed in 16d2762b.

[Phonograph Plus Preview Channel Release 16d2762b](https://github.com/chr56/Phonograph_Plus/files/15281719/Phonograph_PreviewRelease_16d2762b.zip)

**Comment by unnamedau** [comment] 2024-05-12 03:40
that's fixed it, thank you so much!

**Comment by chr56** [comment] 2024-05-12 12:04
Fix has been backported to **Stable channel** release [v1.6.3](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.6.3). Close!

(Also, **Preview channel** release [preview_1.7-beta1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.7-beta1) contains the same fix.)

**Closed** 2024-05-12 12:04 UTC
Labels: Bug, Crash, Device-Specific
