### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FX9590** [chr56/Phonograph_Plus#5] opened 2022-04-07 21:45 UTC
**Describe the bug or unexpected behavior**
Crashed when choose a file to play. Then crased every time when it booted.
Absolutely, data of the app was cleaned before, or i don't have a chance to choose a file.

**Crash log**
If app crashed, copy the logs if available.
Crash Report:

Package name:    player.phonograph.plus
App version:     0.2.0-RC1 (201)
Git Commit Hash: 3bc4bda5f0570f111217
Android version: 12 (SDK 31)
Device brand:    Redmi  (by Xiaomi)
Device model:    M2012K11AC (code: alioth)
Product name:    alioth
Build version:   SKQ1.211006.001 test-keys 
                 (21.12.27)
Hardware:        qcom
Language:        zh

java.lang.ExceptionInInitializerError
	at v3.d.<clinit>(Unknown Source:11)
	at v3.c.a(Unknown Source:0)
	at V2.g.a(Unknown Source:222)
	at V2.b.b(Unknown Source:2)
	at X2.c.c(Unknown Source:69)
	at O2.b.a(:4)
	at T3.c$c.o(Unknown Source:5)
	at d2.a.e(:2)
	at q2.I.run(Unknown Source:86)
	at kotlinx.coroutines.scheduling.a.u(Unknown Source:0)
	at kotlinx.coroutines.scheduling.a$a.run(:5)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: u3.d.values []
	at java.lang.Enum.enumValues(Enum.java:270)
	at java.lang.Enum.access$000(Enum.java:61)
	at java.lang.Enum$1.create(Enum.java:277)
	at java.lang.Enum$1.create(Enum.java:275)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
	at java.lang.Enum.getSharedConstants(Enum.java:289)
	at java.lang.Class.getEnumConstantsShared(Class.java:2459)
	at java.util.EnumSet.getUniverse(EnumSet.java:407)
	at java.util.EnumSet.noneOf(EnumSet.java:109)
	at java.util.EnumSet.of(EnumSet.java:258)
	at v3.b.<clinit>(Unknown Source:8)
	... 11 more
Caused by: java.lang.NoSuchMethodException: u3.d.values []
	at java.lang.Class.getMethod(Class.java:2103)
	at java.lang.Class.getDeclaredMethod(Class.java:2081)
	at java.lang.Enum.enumValues(Enum.java:267)
	... 21 more

**How to reproduce**
Steps to reproduce the bugs or unexpected 
boot the app, choose a file to play.
behaviors:
Crash

**Comment by chr56** [comment] 2022-04-08 01:18
I am aware of this issue.
It seems that this crash happens when reading tags of ogg audio format. Have you tried other formats?

**Comment by chr56** [comment] 2022-04-08 03:29
> I am aware of this issue. It seems that this crash happens when reading tags of ogg audio format. Have you tried other formats?

It seems your files are flac audio format actually.

**Comment by chr56** [comment] 2022-04-08 03:31
[PhonographPlus_0.2.0-RC1-preview.zip](https://github.com/chr56/Phonograph_Plus/files/8448300/PhonographPlus_0.2.0-RC1-preview.zip)

Try this.
**Note**: please be aware that this is an another app with name `Phonograph Plus Preview`  (along with package name `player.phonograph.plus.preview` ) ,and there would be an another Application named `Phonograph Plus Preview` in your app list!

**Comment by FX9590** [comment] 2022-04-08 07:25
> > I am aware of this issue. It seems that this crash happens when reading tags of ogg audio format. Have you tried other formats?
> 
> It seems your files are flac audio format actually.

Yes，It's flac.

**Comment by FX9590** [comment] 2022-04-08 07:49
> [PhonographPlus_0.2.0-RC1-preview.zip](https://github.com/chr56/Phonograph_Plus/files/8448300/PhonographPlus_0.2.0-RC1-preview.zip)
> 
> Try this. **Note**: please be aware that this is an another app with name `Phonograph Plus Preview` (along with package name `player.phonograph.plus.preview` ) ,and there would be an another Application named `Phonograph Plus Preview` in your app list!

I've tried this version.
It still crash when selected a flac file, and will crash at the next boot, work fine with mp3 and wav. 
When selecte a ogg file you mentioned, It sames as the former version.
There's little differences with crash report. i'll report them later.

**Comment by technopagan** [comment] 2022-04-08 08:29
Can confirm constant crashes since the 2.0 RC release (upgraded via FDroid). Purged application settings etc. all with no effect. Keeps crashing. All my music is MP4 AAC.

**Comment by chr56** [comment] 2022-04-08 10:34
[PhonographPlus_0.2.0-RC1-preview.zip](https://github.com/chr56/Phonograph_Plus/files/8451051/PhonographPlus_0.2.0-RC1-preview.zip)

@technopagan  @FX9590 
This problem should be fixed now. (it caused by invalid ProGuard config)

**Comment by chr56** [comment] 2022-04-11 00:27
If there are no more problems, this issue would be closed soon.

**Closed** 2022-04-12 01:05 UTC
Labels: bug
